#! /usr/bin/bash
select choice1 in backup_data restore_backup
do
    case $choise1 in
        "backup_data")
           if [ -d /$HOME/backup ]; then
                mkdir /$HOME/backup_new
                for file in $HOME;
                do
                    if [ -f $file ] then 
                        cp $file /$HOME/backup_new
                    fi 
                done
                zip -mu /$HOME/backup.zip.bak /$HOME/backup_new
            else
                mkdir /$HOME/backup
                
                for file in $HOME;
                do
                    if [ -f $file ] then 
                        cp $file /$HOME/backup
                    fi 
                done
                zip -mu /$HOME/backup.zip.bak /$HOME/backup
            fi
    ;;
        "restore_backup")
            read -p "Enter backup path: " res_backup
            if [ -f res_backup ]; then
                mkdir /$HOME/restored_backup
                cp $res_backup backup.zip
                unzip  /$HOME/restored_backup/backup.zip
            else 
                echo "wrong backup file"
            fi
    ;;
    esac
done

 